// GERADO POR tool/curate_symbols.dart — NÃO EDITE À MÃO.
//
// Pictogramas: Mulberry Symbols, © Steve Lee,
// licenciados sob CC BY-SA 2.0 UK — https://mulberrysymbols.org
library;

/// Ids dos símbolos SVG realmente embarcados em assets/symbols/.
const Set<String> kBundledSymbolIds = {
  'abracar',
  'abrir',
  'acabou',
  'agua',
  'ajudar',
  'banana',
  'banheiro',
  'banho',
  'beber',
  'bola',
  'bravo',
  'brincar',
  'brinquedo',
  'cachorro',
  'carro',
  'casa',
  'comer',
  'comida',
  'dar',
  'dormir',
  'escola',
  'feliz',
  'fome',
  'fora',
  'gato',
  'ir',
  'leite',
  'maca',
  'mais',
  'mamae',
  'musica',
  'o-que',
  'onde',
  'pao',
  'papai',
  'por-que',
  'quando',
  'quem',
  'quente',
  'querer',
  'roupa',
  'sede',
  'sentar',
  'triste',
  'tv',
  'ver',
};
